### ISSUE TITLE
unrecognized command argument certbot   

### ISSUE THREAD

**Issue by coreybruce** [infinityofspace/certbot_dns_duckdns#121]
**Describe the bug**
Unable to use certbot_dns_duckdns as the command is unrecognized
```
certbot: error: unrecognized arguments: --dns-duckdns-token █████ --dns-duckdns-propagation-seconds 60
```
It can see the plugin is there
```
certbot plugins

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* apache
Description: Apache Web Server plugin
Interfaces: Installer, Authenticator, Plugin
Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT

* dns-duckdns
Description: Obtain certificates using a DNS TXT record for DuckDNS domains
Interfaces: Authenticator, Plugin
Entry point: dns-duckdns = certbot_dns_duckdns.cert.client:Authenticator

* standalone
Description: Spin up a temporary webserver
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Versions (please complete the following version information):**
 - certbot: [you can use `certbot --version` to get the version]
 - certbot_dns_duckdns: [you can use `pip show certbot_dns_duckdns` to get the version]

Certbot version: 1.29.0.1
cerbot_dns_duckdns version: 1.1

**Additional context**

**Comment by infinityofspace** [comment]
Thanks for your report.

Please specify what excat command (of course with removal of any private details) you used in order to reproduce the error.

Also, make sure that you use the certbot command with the same user for which you installed the plugin and not, for example, the root user and a normal user.

**Comment by coreybruce** [comment]
Yeah I'll just close this for now, I would have to come back to this as I'm not using this.

**Comment by AndreyShpilevoy** [comment]
I faced with the same issue.
Command is:
`sudo certbot --agree-tos --email email@example.com --preferred-challenges dns --authenticator dns-duckdns --dns-duckdns-token <TOKEN> --dns-duckdns-propagation-seconds 60 -d domain.duckdns.org --apache  --redirect --hsts --staple-ocsp`

**Comment by infinityofspace** [comment]
> I faced with the same issue. Command is: `sudo certbot --agree-tos --email email@example.com --preferred-challenges dns --authenticator dns-duckdns --dns-duckdns-token <TOKEN> --dns-duckdns-propagation-seconds 60 -d domain.duckdns.org --apache --redirect --hsts --staple-ocsp`
> 
> My plugins:
> ....

You are trying to create a dns-01 challange in your command with the `certbot_dns_duckdns` plugin and at the same time an http-01 challange certificate with `apache`. This does not work with this certbot command at the same time.

Please check the [official certbot documentation](https://eff-certbot.readthedocs.io/en/stable/using.html#combining-plugins) how plugins can be combined.

**Comment by AndreyShpilevoy** [comment]
Clear, thank you for explanation
