### ISSUE TITLE
certbot-dns-duckdns is not available for arm64?

### ISSUE THREAD

**Issue by liutas4x4** [infinityofspace/certbot_dns_duckdns#20]
Hi,

While I was trying to install certbot-dns-duckdns on Amrbian (Buster, Rock Pi 4B), I got:

> error: snap "certbot-dns-duckdns" is not available on this architecture (arm64) but exists on other architectures (amd64)

in respond to 

> snap install certbot-dns-duckdns

My final target is accessing OMV NAS with help of letsencrypt.

Any solution?

Eugenius.

**Comment by infinityofspace** [comment]
The first initial edge channel version is only available for the amd64 architecture. For the upcoming stable channel release the plugin will be built for multi arch. This will include a build for the architecture arm64.

**Comment by liutas4x4** [comment]
have you any milestone for this update?

**Comment by infinityofspace** [comment]
You can now find snap builds for the architectures armhf, arm64 (armv8) and amd64 in the [snap store](https://snapcraft.io/certbot-dns-duckdns) beta channel.

**Comment by liutas4x4** [comment]
Thank you. It seems it is working.
