### ISSUE TITLE
Undeclared dependency on dnspython

### ISSUE THREAD

**Issue by alexzorin** [infinityofspace/certbot_dns_duckdns#22]
**Describe the bug**
In https://github.com/infinityofspace/certbot_dns_duckdns/commit/b3183bdbb2817c5288e83e203b791939e09d9c60, this plugin became dependent on the `dnspython` module, but did not explicitly declare that dependency. 

We received a report at https://community.letsencrypt.org/t/no-module-named-dns/169350 which appears to be a result of that omission.

**To Reproduce**
See thread.

**Expected behavior**
See thread

**Certbot command**
See thread

**Versions (please complete the following version information):**
 - certbot: 1.22
 - certbot_dns_duckdns: 0.7

**Comment by infinityofspace** [comment]
Thanks for your bug report.
Unfortunately the dependency slipped through as it was already added for manual builds. The bug will be fixed in the upcoming version `v0.7.1`.
