### ISSUE TITLE
setup.py: Undeclared dependency on dnspython / setup.py and requirements.txt are out of sync

### ISSUE THREAD

**Issue by MaxPeal** [infinityofspace/certbot_dns_duckdns#23]
**Describe the bug**
in the setup.py are Undeclared dependency / setup.py and requirements.txt are out of sync

**To Reproduce**
pip3 install certbot_dns_duckdns

**Comment by infinityofspace** [comment]
Thanks for your bug report.

The dependencies unfortunately slipped through in the last release.
